In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.autograd import Variable

In [3]:
R = Variable(torch.zeros(1,10))
R = R + 1
print R

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])


In [4]:
R = torch.zeros(1,10)
print R

tensor([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])


In [5]:
r = torch.zeros(1, 1)

In [6]:
r.cuda()

tensor([[ 0.]], device='cuda:0')

In [12]:
a = Variable(torch.zeros(3))
a[0] = 1
a[1] = 2
a[2] = 3
print a
a[0].copy_(a[-1])
print a

tensor([ 1.,  2.,  3.])
tensor([ 3.,  2.,  3.])
